google_api:
  key: "${GOOGLE_API_KEY}"
  search_engine_id: "${GOOGLE_SEARCH_ENGINE_ID}"

database:
  sqlite_path: "/Users/estheragossa/PycharmProjects/ift_coursework_2024_final//000.Database/SQL/Equity.db"
  mongo_uri: "mongodb://localhost:27020/"
  mongo_db: "csr_reports_db2"
  mongo_collection: "reports"

minio:
  endpoint: "localhost:9002"
  access_key: "ift_bigdata"
  secret_key: "minio_password"
  bucket_name: "csr-reports1"